add systemd-networkd package; improve octavia-interface systemd service and octavia-interface script.

diff --git a/templates/redhat/opt/octavia-interface.sh.j2 b/templates/redhat/opt/octavia-interface.sh.j2
--- a/templates/redhat/opt/octavia-interface.sh.j2
+++ b/templates/redhat/opt/octavia-interface.sh.j2
@@ -1,11 +1,19 @@
 #!/bin/bash
 
-set -ex
-
 MAC={{ lb_mgmt_port_mac }}
 BRNAME=brq{{ lb_network_id[:11] }}
 
 if [ "$1" == "start" ]; then
+  # check if BRNAME exists up to 30 seconds.
+  i=0
+  until [ -d /sys/devices/virtual/net/$BRNAME ]; do
+    if [ "$i" = "10" ]; then
+      echo "Abort: $BRNAME does not exist."
+      exit 1
+    fi
+    sleep 3
+    ((i++))
+  done
   ip link add o-hm0 type veth peer name o-bhm0
   brctl addif $BRNAME o-bhm0
   ip link set o-bhm0 up
